stages:
  - build
  - deploy

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh-client rsync
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - rsync -avz --delete $CI_REGISTRY_IMAGE:latest $DEPLOY_USER@$DEPLOY_SERVER:/path/to/destination
  only:
    - master

  